import XCTest
import AppKit
@testable import OpenSelection

/// Regression guard for the clipboard-manager ghost-entry race (Maccy et al.).
///
/// The copy engine briefly puts an *unmarked* synthetic copy on the pasteboard before restoring the
/// snapshot. A manager that polls `changeCount` and records anything without the nspasteboard
/// transient markers will capture that copy as a bogus history entry. The exposure window is exactly
/// the time between the synthetic write and the restore, so this guards the invariant that **no
/// suspension point sits between them**: reintroducing an `await` there (commit f58c219 added a 30 ms
/// sleep that produced a measured 6.5% ghost rate against real Maccy) makes this test fail.
///
/// The stand-in observer shares the main actor with the engine, so it can only sample at suspension
/// points — i.e. it proves the synchronous invariant above, not what a separate-process manager sees.
/// End-to-end validation against the real Maccy app is done out of band, not in CI.
final class ClipboardManagerGhostTests: XCTestCase {
    private static let pasteboardName = NSPasteboard.Name("com.openselection.tests.maccyghost")

    @MainActor
    private func makePasteboard() -> NSPasteboard {
        let pasteboard = NSPasteboard(name: Self.pasteboardName)
        pasteboard.clearContents()
        return pasteboard
    }

    /// Mirrors Maccy's `Clipboard.checkForChangesInPasteboard`:
    ///   `guard pasteboard.changeCount != changeCount else { return }`
    ///   `changeCount = pasteboard.changeCount`
    ///   ignore when the types intersect { transient, autoGenerated, concealed }
    ///   otherwise record the string as a history entry.
    private final class FakeMaccy: @unchecked Sendable {
        static let ignored: Set<NSPasteboard.PasteboardType> = [
            NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
            NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
            NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
            NSPasteboard.PasteboardType("x.nspasteboard.ModifiedType")
        ]

        private let pasteboard: NSPasteboard
        private let interval: TimeInterval
        // Maccy polls on the main runloop (Timer.scheduledTimer); NSPasteboard reads must stay on
        // one thread, so the stand-in polls on main too.
        private let queue = DispatchQueue.main
        private let timer: DispatchSourceTimer
        private let lock = NSLock()
        private var lastChangeCount: Int
        private var recorded: [String] = []

        var entries: [String] { lock.withLock { recorded } }

        init(pasteboard: NSPasteboard, interval: TimeInterval) {
            self.pasteboard = pasteboard
            self.interval = interval
            self.lastChangeCount = pasteboard.changeCount
            self.timer = DispatchSource.makeTimerSource(queue: queue)
        }

        func start() {
            timer.schedule(deadline: .now(), repeating: interval, leeway: .microseconds(10))
            timer.setEventHandler { [weak self] in self?.tick() }
            timer.resume()
        }

        func stop() { timer.cancel() }

        private func tick() {
            let count = pasteboard.changeCount
            guard count != lastChangeCount else { return }
            lastChangeCount = count

            let types = Set(pasteboard.types ?? [])
            guard types.isDisjoint(with: Self.ignored) else { return }
            guard let text = pasteboard.string(forType: .string),
                  !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
            else { return }
            lock.withLock { recorded.append(text) }
        }
    }

    @MainActor
    func testMaccyRecordsNoGhostEntryDuringSyntheticCopy() async throws {
        let pasteboard = makePasteboard()
        pasteboard.setString("Original", forType: .string)

        let maccy = FakeMaccy(pasteboard: pasteboard, interval: 0.001) // aggressive poller
        maccy.start()
        defer { maccy.stop() }
        try? await Task.sleep(nanoseconds: 20_000_000) // let the poller settle

        let engine = PasteboardCopyEngine()
        for i in 0..<10 {
            _ = await engine.capture(pasteboard: pasteboard) {
                pasteboard.clearContents()
                pasteboard.setString("Synthetic \(i)", forType: .string)
            }
        }

        maccy.stop()
        let ghosts = maccy.entries
        XCTAssertEqual(
            ghosts.count, 0,
            "clipboard manager recorded \(ghosts.count) ghost entries: \(ghosts)"
        )
    }
}
