import XCTest
import AppKit
@testable import OpenSelection

final class PasteboardCopyEngineTests: XCTestCase {
    private static let pasteboardName = NSPasteboard.Name("com.openselection.tests.copyengine")

    @MainActor
    private func makePasteboard() -> NSPasteboard {
        let pasteboard = NSPasteboard(name: Self.pasteboardName)
        pasteboard.clearContents()
        return pasteboard
    }

    @MainActor
    func testTriggerChangesContentReturnsNewStringRestoresOriginalWithTransientMarkers() async throws {
        let pasteboard = makePasteboard()
        pasteboard.setString("Original", forType: .string)

        let engine = PasteboardCopyEngine()
        let captured = await engine.capture(pasteboard: pasteboard) {
            pasteboard.clearContents()
            pasteboard.setString("Copied", forType: .string)
        }

        XCTAssertEqual(captured?.text, "Copied")
        XCTAssertEqual(pasteboard.string(forType: .string), "Original")

        let transient = pasteboard.data(forType: NSPasteboard.PasteboardType(rawValue: "org.nspasteboard.TransientType")) ?? Data()
        let autoGenerated = pasteboard.data(forType: NSPasteboard.PasteboardType(rawValue: "org.nspasteboard.AutoGeneratedType")) ?? Data()
        XCTAssertEqual(transient, Data())
        XCTAssertEqual(autoGenerated, Data())
    }

    @MainActor
    func testTriggerWritingBackSameTextReturnsText() async throws {
        let pasteboard = makePasteboard()
        pasteboard.setString("Original", forType: .string)

        let engine = PasteboardCopyEngine()
        let captured = await engine.capture(pasteboard: pasteboard) {
            pasteboard.clearContents()
            pasteboard.setString("Original", forType: .string)
        }

        XCTAssertEqual(captured?.text, "Original")
    }

    @MainActor
    func testTimeoutWithUntouchedPasteboardDoesNotRestoreOrAlterChangeCount() async throws {
        let pasteboard = makePasteboard()
        pasteboard.setString("Original", forType: .string)
        let initialChangeCount = pasteboard.changeCount

        let engine = PasteboardCopyEngine()
        let captured = await engine.capture(
            pasteboard: pasteboard,
            timeout: 0.05,
            restoreDelay: 0.05
        ) {
            // No-op
        }

        XCTAssertNil(captured)
        XCTAssertEqual(pasteboard.string(forType: .string), "Original")
        XCTAssertEqual(pasteboard.changeCount, initialChangeCount)
        XCTAssertNil(pasteboard.data(forType: PasteboardSnapshot.transientType))
        XCTAssertNil(pasteboard.data(forType: PasteboardSnapshot.autoGeneratedType))
    }

    @MainActor
    func testTimeoutWithModifiedPasteboardRestoresOriginalWithTransientMarkers() async throws {
        let pasteboard = makePasteboard()
        pasteboard.setString("Original", forType: .string)

        let engine = PasteboardCopyEngine()
        let captured = await engine.capture(
            pasteboard: pasteboard,
            timeout: 0.05,
            restoreDelay: 0.05
        ) {
            pasteboard.clearContents()
            pasteboard.setString("   ", forType: .string)
        }

        XCTAssertNil(captured)
        XCTAssertEqual(pasteboard.string(forType: .string), "Original")
        XCTAssertNotNil(pasteboard.data(forType: PasteboardSnapshot.transientType))
        XCTAssertNotNil(pasteboard.data(forType: PasteboardSnapshot.autoGeneratedType))
    }

    @MainActor
    func testSnapshotCapturePreservesLazyAndPromisedTypes() throws {
        let pasteboard = makePasteboard()
        let item = NSPasteboardItem()
        item.setDataProvider(DummyLazyDataProvider(), forTypes: [.string])
        pasteboard.writeObjects([item])

        let snapshot = PasteboardSnapshot.capture(pasteboard)
        XCTAssertEqual(snapshot.items.count, 1)
        XCTAssertTrue(snapshot.items[0].types.contains(.string))
    }

    @MainActor
    func testHasSelection() {
        XCTAssertTrue(PasteboardCopyEngine.hasSelection("hello"))
        XCTAssertFalse(PasteboardCopyEngine.hasSelection(""))
        XCTAssertFalse(PasteboardCopyEngine.hasSelection("   \n \t  "))
        XCTAssertFalse(PasteboardCopyEngine.hasSelection(nil))
    }

    @MainActor
    func testBrowserPollingTimeout() {
        XCTAssertEqual(PasteboardCopyEngine.pollingTimeout(for: "com.apple.Safari"), SelectionConfiguration.default.safariPasteboardCopyTimeout)
        XCTAssertEqual(PasteboardCopyEngine.pollingTimeout(for: "com.google.Chrome"), SelectionConfiguration.default.safariPasteboardCopyTimeout)
        XCTAssertEqual(PasteboardCopyEngine.pollingTimeout(for: "com.apple.TextEdit"), SelectionConfiguration.default.pasteboardCopyTimeout)
    }
}

private final class DummyLazyDataProvider: NSObject, NSPasteboardItemDataProvider {
    func pasteboard(_ pasteboard: NSPasteboard?, item: NSPasteboardItem, provideDataForType type: NSPasteboard.PasteboardType) {
        // Deliberately empty
    }
}
